title: 'AWS NOAA GPCP PRECIP MONTHLY'
description: 'The Global Precipitation Climatology Project (GPCP) Monthly Precipitation Climate Data Record (CDR) consists of monthly satellite-gauge and associated precipitation error estimates taken from January 1979–present. The CDR is created by combining the precipitation information from several satellite and in situ sources into a final merged product that uses the strengths of each data type to create a more accurate record.'
pangeo_forge_version: '0.9.2'
pangeo_notebook_version: '2021.07.17'
recipes:
  - id: AWS NOAA GPCP precip monthly
    object: 'recipe:recipe'
provenance:
  providers:
    - name: 'AWS NOAA GPCP precip monthly'
      description: 'Registry of Open Data on AWS National Oceanographic & Atmospheric Administration National Centers for Environmental Information'
      roles:
        - producer
        - licensor
      url: s3://noaa-cdr-precip-gpcp-monthly-pds/
  license: 'Open Data'
maintainers:
  - name: 'Ruben L. Mendoza'
    orcid: '0000-0001-5880-7243'
    github: Rub21
bakery:
  id: 'pangeo-noaa-cdr-precip-gpcp-monthly-pds'
