title: 'AWS NOAA Optimum Interpolated SST'
description: 'Analysis-ready datasets derived from AWS NOAA OISST NetCDF'
pangeo_forge_version: '0.9.2'
recipes:
  - id: aws-noaa-oisst-avhrr-only
    object: 'recipe:recipe'
provenance:
  providers:
    - name: 'AWS NOAA Oceanic CDR'
      description: 'Registry of Open Data on AWS National Oceanographic & Atmospheric Administration National Centers for Environmental Information'
      roles:
        - producer
        - licensor
      url: s3://noaa-cdr-sea-surface-temp-optimum-interpolation-pds
  license: 'Open Data'
maintainers:
  - name: 'Ryan Avery'
    orcid: '0000-0001-7392-1474'
    github: rbavery
bakery:
  id: 'devseed.bakery.development.aws.us-west-2' # must come from a valid list of bakeries
  target: pangeo-forge-aws-bakery-flowcachebucketdasktest4-10neo67y7a924
  resources:
    memory: 4096
    cpu: 1024
