title: 'AWS NOAA Terrestrial CDR NDVI'
description: 'Analysis-ready datasets derived from AWS NOAA Terrestrial CDR Normalized Difference Vegetation Index (NDVI) NetCDF. This global 0.05° resolution daily product is available from 1981—to 10 days before present. Inputs into the calculation of the NDVI product are provided by the AHVRR Surface Reflectance-Climate Data Record from 1981 to 2013. Whereas inputs into the calculation of the NDVI product are provided by the Visible Infrared Imaging Radiometer Suite (VIIRS) Surface Reflectance from 2014 to present. Potential use cases of this data record include: detecting drought-stressed regions, forecasting agricultural yields, forestry and crop management, etc'
pangeo_forge_version: '0.9.2'
pangeo_notebook_version: '2021.07.17'
recipes:
  - id: aws-noaa-cdr-ndvi
    object: 'recipe:recipe'
provenance:
  providers:
    - name: 'AWS NOAA Terrestrial CDR'
      description: 'Registry of Open Data on AWS National Oceanographic & Atmospheric Administration National Centers for Environmental Information'
      roles:
        - producer
        - licensor
      url: s3://noaa-cdr-ndvi-pds/
  license: 'Open Data'
maintainers:
  - name: 'Kathryn Berger'
    orcid: '0000-0001-9731-6519'
    github: kathrynberger
bakery:
  id: 'pangeo-ldeo-nsf-earthcube'
