title: 'AWS NOAA SOLAR SPECTRAL IRRADIANCE DAILY'
description: 'This Climate Data Record (CDR) contains solar spectral irradiance (SSI) as a function of time and wavelength created with the Naval Research Laboratory model for spectral and total irradiance (version 2). Solar spectral irradiance is the wavelength-dependent energy input to the top of the Earth's atmosphere, at a standard distance of one Astronomical Unit from the Sun. Its units are W per m2 per nm. Also included is the value of total (spectrally integrated) solar irradiance in units W per m2. The dataset was created by Judith Lean (Space Science Division, Naval Research Laboratory), Odele Coddington and Peter Pilewskie (Laboratory for Atmospheric and Space Science, University of Colorado). The daily- and monthly-averaged SSI data range from 1882 to the present, and annual-averaged SSI data begin in 1610. The data file format is netCDF-4 following CF metadata conventions. The dataset is accompanied by algorithm documentation, data flow diagram and source code for the NOAA CDR Program.'
pangeo_forge_version: '0.9.2'
pangeo_notebook_version: '2021.07.17'
recipes:
  - id: aws-noaa-solar-irradiance-daily
    object: 'recipe:recipe'
provenance:
  providers:
    - name: 'AWS NOAA Solar spectral irradiance daily'
      description: 'Registry of Open Data on AWS National Oceanographic & Atmospheric Administration National Centers for Environmental Information'
      roles:
        - producer
        - licensor
      url: s3://noaa-cdr-solar-spectral-irradiance-pds/
  license: 'Open Data'
maintainers:
  - name: 'Ruben L. Mendoza'
    orcid: '0000-0001-5880-7243'
    github: Rub21
bakery:
  id: 'pangeo-aws-solar-spectral-irradiance-daily'
